version: '3.5'

services:
  billtrackerapp.api:
    image: ${DOCKER_REGISTRY-}billtrackerappapi
    build:
      context: .
      dockerfile: BillTrackerApp.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
