// <auto-generated />
using System;
using BillTrackerApp.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BillTrackerApp.API.Migrations
{
    [DbContext(typeof(BillTrackerContext))]
    [Migration("20200525052449_initcreate")]
    partial class initcreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("BillTrackerApp.API.Models.Address", b =>
                {
                    b.Property<int>("AddressID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City")
                        .HasMaxLength(200);

                    b.Property<int>("CompanyID");

                    b.Property<string>("Country")
                        .HasMaxLength(50);

                    b.Property<string>("State")
                        .HasMaxLength(50);

                    b.Property<string>("StreetAddress1")
                        .HasMaxLength(500);

                    b.Property<string>("StreetAddress2")
                        .HasMaxLength(500);

                    b.Property<string>("Zip")
                        .HasMaxLength(15);

                    b.HasKey("AddressID");

                    b.HasIndex("CompanyID")
                        .IsUnique();

                    b.ToTable("Address");
                });

            modelBuilder.Entity("BillTrackerApp.API.Models.Company", b =>
                {
                    b.Property<int>("CompanyID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .HasMaxLength(500);

                    b.Property<string>("Phone")
                        .HasMaxLength(30);

                    b.Property<DateTime>("StartDate");

                    b.HasKey("CompanyID");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("BillTrackerApp.API.Models.Invoice", b =>
                {
                    b.Property<int>("InvoiceID")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("AmountDue");

                    b.Property<decimal>("AmountPaid");

                    b.Property<decimal>("Balance");

                    b.Property<DateTime>("BillingPeriod");

                    b.Property<int>("CompanyID");

                    b.Property<string>("ConfirmationNumber")
                        .HasMaxLength(100);

                    b.Property<DateTime>("DatePaid");

                    b.Property<DateTime>("DueDate");

                    b.Property<string>("Note");

                    b.HasKey("InvoiceID");

                    b.HasIndex("CompanyID");

                    b.ToTable("Invoice");
                });

            modelBuilder.Entity("BillTrackerApp.API.Models.Address", b =>
                {
                    b.HasOne("BillTrackerApp.API.Models.Company", "Company")
                        .WithOne("CompanyAddress")
                        .HasForeignKey("BillTrackerApp.API.Models.Address", "CompanyID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BillTrackerApp.API.Models.Invoice", b =>
                {
                    b.HasOne("BillTrackerApp.API.Models.Company", "Company")
                        .WithMany("Invoices")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
